// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8XflYwXp5q9ONDD9iC5hWXHn4rmhV5LM',
    appId: '1:318456524749:web:054a736379b88867eb5e84',
    messagingSenderId: '318456524749',
    projectId: 'hearts-36da3',
    authDomain: 'hearts-36da3.firebaseapp.com',
    databaseURL: 'https://hearts-36da3-default-rtdb.firebaseio.com',
    storageBucket: 'hearts-36da3.appspot.com',
    measurementId: 'G-FPD0SFRKGR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDx1ymEbZdBGgsWCLfMFUgcaFGZbKKY-vE',
    appId: '1:318456524749:android:ad00b025cb5a4f17eb5e84',
    messagingSenderId: '318456524749',
    projectId: 'hearts-36da3',
    databaseURL: 'https://hearts-36da3-default-rtdb.firebaseio.com',
    storageBucket: 'hearts-36da3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYuc_IDKyGgb66fonJ8jZta7h-6knHPoc',
    appId: '1:318456524749:ios:f198d887a8380132eb5e84',
    messagingSenderId: '318456524749',
    projectId: 'hearts-36da3',
    databaseURL: 'https://hearts-36da3-default-rtdb.firebaseio.com',
    storageBucket: 'hearts-36da3.appspot.com',
    androidClientId: '318456524749-6bf0evg8ia0m3f9udvenpa2r6a2tkna6.apps.googleusercontent.com',
    iosClientId: '318456524749-ccgffr631hqlr5dv4tcmj74lr253q10o.apps.googleusercontent.com',
    iosBundleId: 'et.heartsorg.hearts',
  );
}
